### ISSUE TITLE
Disconnected issue in iOS

### ISSUE THREAD

**Issue by sallyoga** [boskokg/flutter_blue_plus#10]
When device is disconnected (not manually) instead of sending a 'disconnect' event, a 'connecting' event is sent.

**Comment by sophisticode** [comment]
I have the same problem. In my case, I turn off the power of the device and the mobile device tries to reconnect. In the log, I can see
'didDisconnectPeripheral:trying reconnect'.
It seems that commit c7bbdf0c8dbf808c5081a8db8ed00c4eb0bce4ef (Ios : try reconnect on unexpected disconnection (fixed by EB-Plum)) introduced that problem.

**Comment by sophisticode** [comment]
Created #11 for fixing this

**Comment by boskokg** [comment]
fixed on 1.1.2
