### ISSUE TITLE
doesn't display names of bluetooth list IOS IPHONE DEVICE,

### ISSUE THREAD

**Issue by insysinfo** [boskokg/flutter_blue_plus#176]
doesn't display names of bluetooth list IOS IPHONE DEVICE, but on android device displaying Name with Address so user easily with connect and know about connect with which device...
in IOS, we are getting only some ids of bluetooth list also number of devices list(unnecessary devices)

pls check below SS...
https://user-images.githubusercontent.com/70749329/209533013-4a69c1d2-eee3-46eb-b497-464e57bc0778.png

@boskokg  pls help me

**Comment by abelherl** [comment]
I have this issue as well, I cannot get the name of this device https://star-m.jp/eng/products/s_print/mpop/index.html

It is found inside the iOS Bluetooth setting page but it doesn't have any name when scanned using flutter_blue_plus. Is there any way this can be fixed? Because I can't even try to connect it by matching the mac address with my Android build because Apple doesn't allow mac address usage.

**Comment by kevinconcourse** [comment]
Facing the same issue

**Comment by kevinconcourse** [comment]
What this issue has been closed? @boskokg

**Comment by boskokg** [comment]
Hello @kevinconcourse ,
This is not a paid plugin, you have all the code needed to perform investigation in the xcode and see what is the issue with the device. If you want to be fixed, please add PR with the fix.
