### ISSUE TITLE
Flutter_blue_plus scan not working when the device screen is off 

### ISSUE THREAD

**Issue by jmiguelmh** [boskokg/flutter_blue_plus#327]
I'm currently creating an app that scans periodically for bluetooth devices. The bluetooth scan must run in background. To achieve this I'm using the flutter_background_service package and it works partially. The bluetooth scan detects devices with the app open (in foreground), minimized or even closed (in background). The user always sees a notification to know that the app is running in background. There's only one case where it doesn't work and it is when the device screen is off (i. e. pressing power button).
I've been investigating this issue and apparently since Android 8.1 when the screen is off, unfiltered scans will show no results. I think there's a workaround to this issue by using the withServices optional parameter of the startScan method. This parameter must receive a List with the UUID services I want to filter.
Here is where my understanding of the topic ends. Does anyone with knowledge in this subject can explain to me in more detail if it's possible to detect bluetooth devices (normal or similar flutter_blue_plus scan behavior) while using a filter. Passing an empty list does not solve the issue, I've already tried.
If not possible, does anyone knows another workaround?
Thanks in advance

**Comment by Daniel-Harding** [comment]
We wanted this capability also but it appears that the OS restricts background scans to last for less than 30 seconds after the screen goes dark or even if the application is not longer in the foreground.  It seems like a background scan should be possible with the screen off because audio players work under that scenario; HOWEVER, there is a critical difference, Android and iOS allow background Bluetooth to work IF it is paired and the device type is allowed (like audio applications) but not just for scans like it appears we want to do.  Ultimately, we were not able to find any method to accomplish this and thus our application will NOT scan in the background... if you find a solution it would be great to hear it... I don't think one exists because Android locked this down in version 8.1 (to save customers battery life) so this would only work in very old phones so not practical for a new cell phone application.
