### ISSUE TITLE
Breaking changes in point releases

### ISSUE THREAD

**Issue by sqcsabbey** [boskokg/flutter_blue_plus#407]
I just upgraded from 1.8.4 to 1.8.8, and it looks like BluetoothState and BluetoothDeviceState are no longer available (or got renamed). 

The minor and point release versions are expected to be backwards compatible, and many consumers of this plugin will be using [caret syntax](https://dart.dev/tools/pub/dependencies#caret-syntax) to pull it in:

> Caret syntax is a compact way of expressing the most common sort of version constraint. ^version means the range of all versions guaranteed to be backwards compatible with the specified version.
> 
> For example, ^1.2.3 is equivalent to '>=1.2.3 <2.0.0', and ^0.1.2 is equivalent to '>=0.1.2 <0.2.0'.

This isn't an issue for me, I'll get this working and I'll pin my version precisely, but changes like this will affect others.

**Comment by MrCsabaToth** [comment]
I'm following the changes closely as well, so it didn't crush me, however now that you say you are right. According to [Semantic Versioning](https://semver.org/) breaking changes would require major version bump. However in the past I've been through numerous non major upgrades with various other plugins where there were such - I'd say - minor (because only requires some renaming) breaking changes without major version increase. These breaking changes are the least of my problems right now, I can deal with them rather than carrying abandoned plugins on my back just so my app keeps functioning. Especially that Bluetooth is the cornerstone of my app.

(I almost did the Android ProtoBuf removal (#338) and it's a big undertaking. I expected that there will be some transient periods like we see now. I'd like to thank @chipweinberger for the ton of work he did the last weeks. I think we are close to the point when the source stabilizes.)

**Comment by chipweinberger** [comment]
thanks for the acknowledgment. Yes I'm really trying to get this package to be very stable and reliable and perfect.

The renamed variables, all have replacements. Just use the new names. They should automatically show up for you because I mark them deprecated.

**Comment by MrCsabaToth** [comment]
> thanks for the acknowledgment. Yes I'm really trying to get this package to be very stable and reliable and perfect.
> 
> The renamed variables, all have replacements. Just use the new names. They should automatically show up for you because I mark them deprecated.

The renames are logical BTW. Id was too overloaded, I had a lot of `id.id` in my code. Also the other renames.

**Comment by chipweinberger** [comment]
There should be no breaking changes besides renames. Let me know if you find others.

**Comment by ekuleshov** [comment]
@chipweinberger that you for your work on improving and fixing `flutter_blue_plus` package. It is most appreciated.

However some of the renames aren't justified. Especially given that this package used in a lot of code. For example meaning of `uuid` field in `BluetoothService` or `BluetoothCharacteristic` is already clear based on the class name and if needed you could clarify that in the doc comment instead of renaming.

The deprecated fields don't directly break the existing code, but in many cases they have to be cleaned up in order for dart/flutter build to pass. And disabling lint rules is not an option there. E.g. one of my projects had over 50 warnings on these deprecated fields and those can't be automatically cleaned up, so it was a manual work required in order to use the latest `flutter_blue_plus` package.

**Comment by MrCsabaToth** [comment]
Also don't forget to regenerate the mocks of these classes for tests

**Comment by chipweinberger** [comment]
@ekuleshov, yes it is a fair point about uuid.  That change is mostly for internal FlutterBluePlus code.

I've added back uuid as a shorthand accessor.

```
class BluetoothCharacteristic {

  // convenience accessor
  Guid get uuid => characteristicUuid;
}
```

class BluetoothService {

  // convenience accessor
  Guid get uuid => serviceUuid;
}
